apiVersion: codriverlabs.ai.toe.run/v1alpha1
kind: PowerTool
metadata:
  name: aperf-collector
  namespace: toe-test
spec:
  targets:
    labelSelector:
      matchLabels:
        app: nginx-cluster
    container: "main-container"
  tool:
    name: "aperf"
    duration: "10s"
    warmup: "5s"
  output:
    mode: "collector"
    collector:
      endpoint: "https://toe-collector.toe-system.svc.cluster.local:8443"
  failurePolicy:
    onError: "stop"
    backoff:
      initial: "10s"
      max: "5m"
      multiplier: "2"
