---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profiling-data-pvc
  namespace: toe-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "microk8s-hostpath" # change to your cluster's storage class for RWX
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-cluster
  namespace: toe-test
spec:
  serviceName: nginx-cluster
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cluster
  template:
    metadata:
      labels:
        app: nginx-cluster
    spec:
      nodeSelector:
        karpenter.sh/capacity-type: spot
      tolerations:
      - key: karpenter.sh/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      containers:
      - name: main-container
        image: public.ecr.aws/docker/library/nginx:latest
        volumeMounts:
        - name: profiling-storage
          mountPath: /profiler_data
      volumes:
      - name: profiling-storage
        persistentVolumeClaim:
          claimName: profiling-data-pvc
