---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profiling-data-pvc
  namespace: toe-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cluster
  namespace: toe-test
  labels:
    app: "nginx-cluster"
spec:
  containers:
  - name: main-container
    image: nginx
    volumeMounts:
    - name: profiling-storage
      mountPath: /profiler_data
  volumes:
  - name: profiling-storage
    persistentVolumeClaim:
      claimName: profiling-data-pvc
