apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profiles-pvc
  namespace: toe-system
spec:
  accessModes:
    - ReadWriteMany  # RWX for multi-pod access
  resources:
    requests:
      storage: 10Gi
  # storageClassName: ""  # Use default storage class
