apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: toe-system
  labels:
    app: pvc-inspector
spec:
  containers:
  - name: inspector
    image: public.ecr.aws/docker/library/busybox:stable
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: profiles-data
      mountPath: /data
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: profiles-data
    persistentVolumeClaim:
      claimName: profiles-pvc
  restartPolicy: Always
