name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Generate code
        run: make generate

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

  # gosec:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Set up Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: '1.24'

  #     - name: Run Gosec Security Scanner
  #       uses: securecodewarrior/github-action-gosec@master
  #       with:
  #         args: '-fmt sarif -out gosec.sarif ./...'

  #     - name: Upload SARIF file
  #       uses: github/codeql-action/upload-sarif@v4
  #       with:
  #         sarif_file: gosec.sarif

  # trivy-fs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Run Trivy vulnerability scanner in fs mode
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'fs'
  #         scan-ref: '.'
  #         format: 'sarif'
  #         output: 'trivy-results.sarif'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v4
  #       if: always()
  #       with:
  #         sarif_file: 'trivy-results.sarif'
